---
sidebar: sidebar 
permalink: use/report-create.html 
keywords: BlueXP migration reports, volume reports 
summary: Con il servizio BlueXP Migration Reports, puoi identificare rapidamente il numero di file, directory, collegamenti simbolici, hard link, la profondità e la larghezza degli alberi dei file system, i file più grandi e molto altro nel tuo ambiente di storage. 
---
= Creare un report
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
È possibile creare un report sui volumi che mostri il numero di file, i file nelle directory, i collegamenti simbolici, i collegamenti hardware, le dimensioni dei file più grandi, e molto altro ancora.

Ogni volta che si crea un report, il servizio di report di migrazione BlueXP esegue la scansione del percorso e compila i dati. Utilizzando la stessa definizione di report, è possibile avere più istanze di quel report.

Il servizio BlueXP Migration Reports mostra i dati in base ai volumi.

È possibile generare un solo report alla volta.

È inoltre possibile scaricare il report come file PDF.


TIP: Tutte le operazioni dei report di migrazione BlueXP sono elencate nella timeline di BlueXP. Per visualizzare la cronologia, selezionare BlueXP *Impostazioni* > *Timeline*.

.Fasi
. Dal navigatore di sinistra BlueXP, selezionare *Storage* > *Migration Reports* (Storage* > rapporti migrazione).
. Selezionare *Crea nuovo report*.
. Immettere un nome per il report.
. Selezionare un ambiente di lavoro dall'elenco a discesa.
+
Solo gli ambienti attivi e abilitati in BlueXP vengono visualizzati nell'elenco degli ambienti di lavoro.

+

TIP: Per accedere ai dati, BlueXP Connector deve disporre dell'accesso al LIF dei dati del volume.

+
Se si desidera attivare un ambiente, fare riferimento a. https://docs.netapp.com/us-en/cloud-manager-setup-admin/concept-connectors.html#when-a-connector-is-required["Scopri di più sui connettori nella documentazione di BlueXP"].

. Utilizzando l'icona *Cerca*, cercare il volume su cui si desidera creare il report o scegliere dall'elenco.
. Selezionare il volume.
. Selezionare *Crea report*.
+
Il servizio BlueXP Migration Reports genera il report e lo elenca nell'elenco dei report.

. Per visualizzare il report, selezionare *Actions* ... A destra e selezionare *Visualizza report*.
. Per scaricare un file PDF del report, selezionare *Actions* ... E selezionare *Scarica report*.
. Per generare un'altra istanza dello stesso report, selezionare la riga del report e, a destra, selezionare *Aggiungi report*.

