---
sidebar: sidebar 
permalink: get-started/intro.html 
keywords: how BlueXP migration reports works, reports, bluexp 
summary: Con il servizio BlueXP Migration Reports, puoi identificare rapidamente il numero di file, directory, collegamenti simbolici, hard link, la profondità e la larghezza degli alberi dei file system, i file più grandi e molto altro nel tuo ambiente di storage. 
---
= Scopri i report sulla migrazione di BlueXP
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/concepts/


[role="lead"]
Quando ci si prepara a spostare, migrare o clonare i dati del file system, occorre innanzitutto determinare le risorse di cui si dispone. Con il servizio BlueXP Migration Reports, puoi identificare rapidamente il numero di file, directory, collegamenti simbolici, hard link, la profondità e la larghezza degli alberi dei file system, i file più grandi e molto altro nel tuo ambiente di storage. Grazie a queste informazioni, saprai in anticipo che il processo che desideri utilizzare può gestire l'inventario in modo efficiente e efficace.

Il servizio BlueXP Migration Reports mostra le informazioni relative agli ambienti di lavoro NFS e AWS S3.



== Vantaggi dei report di migrazione BlueXP

Il servizio BlueXP Migration Reports offre i seguenti vantaggi:

* Fornisce un semplice processo per ottenere lo stato di protezione dei dati dell'ambiente di lavoro
* Offre uno scenario di storage
* Riduce il tempo impiegato per identificare ulteriori esigenze di storage




== Operazioni che è possibile eseguire con i report di migrazione BlueXP

Utilizzando i report di migrazione di BlueXP, è possibile eseguire le seguenti operazioni:

* Creare report.
* Identificare il modo in cui i dati sono cambiati da una data di report a un'altra utilizzando i diagrammi di distribuzione dei report.
* Attivare le notifiche e-mail relative alla generazione dei report.
* Eliminare i report.




== Costo

NetApp non addebita alcun costo per l'utilizzo del servizio.



== Licensing

Non è richiesto un file di licenza NetApp (NLF).
