---
sidebar: sidebar 
permalink: release-notes/whats-new.html 
keywords: 'reports what"s new, bluexp' 
summary: Scopri le novità nei report di migrazione di BlueXP. 
---
= Novità
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Scopri le novità nei report di migrazione di BlueXP.



== 13 novembre 2023

Ora puoi creare report per i volumi che utilizzano il protocollo SMB/CIFS.



== 03 settembre 2023

Il servizio di report di migrazione BlueXP aggiornato fornisce aggiornamenti ai dati dei report. I report ora includono la capacità allocata.



== 02 giugno 2023

Con il nuovo servizio di report sulla migrazione di BlueXP, puoi identificare rapidamente il numero di file, directory, collegamenti simbolici, hard link, profondità e ampiezza degli alberi dei file system, file di grandi dimensioni e altro ancora nel tuo ambiente di storage.

Grazie a queste informazioni, saprai in anticipo che il processo che desideri utilizzare può gestire l'inventario in modo efficiente e efficace.

link:https://docs.netapp.com/us-en/bluexp-reports/get-started/intro.html["Scopri di più sui report di migrazione BlueXP"].
